apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # REVIEWER: Replace placeholders with real credentials
  MONGO_URI: "mongodb+srv://<USER>:<PASSWORD>@<CLUSTER>.mongodb.net/logs"
  KAFKA_BROKER: "pkc-xxxxx.us-east-1.aws.confluent.cloud:9092"
  KAFKA_USERNAME: "YOUR_API_KEY"
  KAFKA_PASSWORD: "YOUR_API_SECRET"